export const categories = [
  "Electronics",
  "Clothing",
  "Home Appliances",
  "Books",
  "Sports & Outdoors",
  "Health & Beauty",
  "Toys & Games",
  "Furniture",
  "Automotive",
  "Jewelry",
  "Baby Products",
  "Pet Supplies",
  "Tools & Home Improvement",
  "Office Supplies",
  "Groceries",
  "Musical Instruments",
  "Outdoor Gear",
  "Watches",
  "Luggage & Travel Gear",
  "Cameras & Photography",
  "Cell Phones & Accessories",
  "Video Games",
  "Movies & TV",
  "Home & Kitchen",
  "Garden & Outdoor",
  "Food & Beverages",
  "Fitness & Exercise",
  "Arts & Crafts",
  "Computers & Accessories",
  "Software",
  "Industrial & Scientific",
  "Beauty & Personal Care",
  "Health & Household",
  "Home Audio & Theater",
  "Kitchen & Dining",
  "Bedding & Bath",
  "Patio, Lawn & Garden",
  "Clothing, Shoes & Jewelry",
  "Electronics & Computers",
  "Toys & Games",
  "Automotive & Industrial",
  "Home & Furniture",
  "Sports & Outdoors",
  "Beauty & Health",
  "Books & Audible",
  "Music, Movies & TV",
  "Grocery & Household",
  "Pet Supplies & Accessories",
  "Office Supplies & Electronics",
  "Tools & Home Improvement",
  "Baby & Kids",
  "Fashion & Accessories",
  "Sports & Fitness",
  "Outdoor & Adventure",
  "Travel & Luggage",
  "Home & Decor",
  "Kitchen & Cooking",
  "Personal Care & Beauty",
  "Electronics & Gadgets",
  "Arts & Crafts Supplies",
  "Educational Toys & Games",
  "Automotive Parts & Accessories",
  "Garden & Outdoor Living",
  "Health & Wellness Products",
  "Fashion & Apparel",
  "Computers & Laptops",
  "Gaming & Entertainment",
  "Home Essentials",
  "Pet Food & Supplies",
  "Business & Office Supplies",
  "Home Improvement Tools",
  "Grocery & Gourmet Food",
  "Fitness & Exercise Equipment",
  "Arts & Entertainment",
  "Travel Accessories",
  "Home Decor & Furnishings",
  "Cooking & Dining Essentials",
  "Beauty & Skincare Products",
  "Audio & Video Equipment",
  "Craft Supplies & Materials",
  "Kids Toys & Games",
  "Auto Parts & Accessories",
  "Outdoor Recreation Gear",
  "Health & Fitness Products",
  "Fashion Accessories & Jewelry",
  "Electronics Accessories",
  "Educational Books & Toys",
  "Gardening Tools & Supplies",
  "Personal Health & Care",
  "Apparel & Accessories",
  "Computers & Peripherals",
  "Gaming Consoles & Accessories",
  "Home Maintenance & Repair",
  "Snacks & Beverages",
  "Exercise & Fitness Gear",
  "Music & Entertainment",
  "Travel Essentials",
  "Home Organization & Storage",
  "Cooking & Baking Supplies",
  "Makeup & Beauty Products"
];
