import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { Navbar } from "./_components/Navbar/Navbar";
import { Announcement } from "./_components/Announcement/Announcemts";
import { UserContextProvider } from "Context/UserContext";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          <UserContextProvider>
            <Navbar />
            <Announcement />
            <main className="h-full mt-[120px] p-8 flex items-center w-full">
              {children}
            </main>
          </UserContextProvider>
        </TRPCReactProvider>
      </body>
    </html >
  );
}
